# coding: utf-8

"""
    MediaStore API

    MediaStore API for MediaStore  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.private_store_api import PrivateStoreApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPrivateStoreApi(unittest.TestCase):
    """PrivateStoreApi unit test stubs"""

    def setUp(self):
        self.api = PrivateStoreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_privatestore_get(self):
        """Test case for privatestore_get

        Gets a list of all the product Ids the user can view.  # noqa: E501
        """
        pass

    def test_privatestore_id_angle_get(self):
        """Test case for privatestore_id_angle_get

        Gets the metadata available for a single image  # noqa: E501
        """
        pass

    def test_privatestore_id_angle_image_get(self):
        """Test case for privatestore_id_angle_image_get

        Gets the binary file for single image  # noqa: E501
        """
        pass

    def test_privatestore_id_get(self):
        """Test case for privatestore_id_get

        Gets a list of images for a given GTIN id  # noqa: E501
        """
        pass

    def test_privatestore_id_main_get(self):
        """Test case for privatestore_id_main_get

        Gets the metadata available for the main image of a product  # noqa: E501
        """
        pass

    def test_privatestore_id_main_image_get(self):
        """Test case for privatestore_id_main_image_get

        Gets the binary file for the main image of a product  # noqa: E501
        """
        pass

    def test_privatestore_productgroup_name_get(self):
        """Test case for privatestore_productgroup_name_get

        Gets a first product for a given product group name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
