# coding: utf-8

"""
    MediaStore API

    MediaStore API for MediaStore  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.media_store_api_features_products_feature_image_dto import MediaStoreAPIFeaturesProductsFeatureImageDto  # noqa: E501
from swagger_client.rest import ApiException


class TestMediaStoreAPIFeaturesProductsFeatureImageDto(unittest.TestCase):
    """MediaStoreAPIFeaturesProductsFeatureImageDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediaStoreAPIFeaturesProductsFeatureImageDto(self):
        """Test MediaStoreAPIFeaturesProductsFeatureImageDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.media_store_api_features_products_feature_image_dto.MediaStoreAPIFeaturesProductsFeatureImageDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
