# coding: utf-8

"""
    MediaStore API

    MediaStore API for MediaStore  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.products_api import ProductsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_products_get(self):
        """Test case for products_get

        Gets a list of all the product Ids the user can view.  # noqa: E501
        """
        pass

    def test_products_getmodifiedgtins_get(self):
        """Test case for products_getmodifiedgtins_get

        Gets a list of gtins that has been modified on given date.  # noqa: E501
        """
        pass

    def test_products_id_angle_get(self):
        """Test case for products_id_angle_get

        Gets the metadata available for a single image  # noqa: E501
        """
        pass

    def test_products_id_angle_image_get(self):
        """Test case for products_id_angle_image_get

        Gets the binary file for a single image  # noqa: E501
        """
        pass

    def test_products_id_badge_angle_get(self):
        """Test case for products_id_badge_angle_get

        Gets the metadata available for a single badge image (Method is not supported anymore)  # noqa: E501
        """
        pass

    def test_products_id_badge_angle_image_get(self):
        """Test case for products_id_badge_angle_image_get

        """
        pass

    def test_products_id_badge_get(self):
        """Test case for products_id_badge_get

        Gets a list of badge images for a given id (Method is not supported anymore)  # noqa: E501
        """
        pass

    def test_products_id_badge_main_get(self):
        """Test case for products_id_badge_main_get

        Gets the metadata available for the main badge image (Method is not supported anymore)  # noqa: E501
        """
        pass

    def test_products_id_badge_main_image_get(self):
        """Test case for products_id_badge_main_image_get

        Gets the binary file for the main badge image of a product (Method is not supported anymore)  # noqa: E501
        """
        pass

    def test_products_id_enriched_angle_get(self):
        """Test case for products_id_enriched_angle_get

        Gets the metadata available for a single enriched image  # noqa: E501
        """
        pass

    def test_products_id_enriched_angle_image_get(self):
        """Test case for products_id_enriched_angle_image_get

        Gets the binary file for a single enriched image  # noqa: E501
        """
        pass

    def test_products_id_enriched_get(self):
        """Test case for products_id_enriched_get

        Gets a list of enriched images for a given id  # noqa: E501
        """
        pass

    def test_products_id_enriched_main_get(self):
        """Test case for products_id_enriched_main_get

        Gets the metadata available for the main enriched image  # noqa: E501
        """
        pass

    def test_products_id_enriched_main_image_get(self):
        """Test case for products_id_enriched_main_image_get

        Gets the binary file for the main enriched image of a product  # noqa: E501
        """
        pass

    def test_products_id_foodservice_packaging_get(self):
        """Test case for products_id_foodservice_packaging_get

        Gets the metadata available for a servering single image  # noqa: E501
        """
        pass

    def test_products_id_foodservice_packaging_image_get(self):
        """Test case for products_id_foodservice_packaging_image_get

        Gets the binary file for a single servering image  # noqa: E501
        """
        pass

    def test_products_id_get(self):
        """Test case for products_id_get

        Gets a list of images for a given id  # noqa: E501
        """
        pass

    def test_products_id_main_get(self):
        """Test case for products_id_main_get

        Gets the metadata available for the main image of a product  # noqa: E501
        """
        pass

    def test_products_id_main_image_get(self):
        """Test case for products_id_main_image_get

        Gets the binary file for the main image of a product  # noqa: E501
        """
        pass

    def test_products_id_recommended_get(self):
        """Test case for products_id_recommended_get

        Gets the metadata available for the suppliers recommended image of a product. If no recommended image is set on the product, then the main image on the product will be delivered  # noqa: E501
        """
        pass

    def test_products_id_recommended_image_get(self):
        """Test case for products_id_recommended_image_get

        Gets the binary file for the suppliers recommended image of a product. If no recommended image is set on the product, then the main image on the product will be delivered  # noqa: E501
        """
        pass

    def test_products_id_space_angle_get(self):
        """Test case for products_id_space_angle_get

        Gets the metadata available for a single image in space format  # noqa: E501
        """
        pass

    def test_products_id_space_angle_image_get(self):
        """Test case for products_id_space_angle_image_get

        Gets the binary file for an image in space format  # noqa: E501
        """
        pass

    def test_products_id_space_get(self):
        """Test case for products_id_space_get

        Gets the list of the images avaliable in space format for a given id.  # noqa: E501
        """
        pass

    def test_products_id_space_main_get(self):
        """Test case for products_id_space_main_get

        Gets the metadata available for the main image of a product in space format  # noqa: E501
        """
        pass

    def test_products_id_space_main_image_get(self):
        """Test case for products_id_space_main_image_get

        Gets the binary file for the main image of a product in space format  # noqa: E501
        """
        pass

    def test_products_imageset_id_valid_from_valid_to_post(self):
        """Test case for products_imageset_id_valid_from_valid_to_post

        Change the from and to date for an imageset  # noqa: E501
        """
        pass

    def test_products_modified_get(self):
        """Test case for products_modified_get

        Gets a list of products that has been modified between two given dates. Both dates are inclusive.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
