# coding: utf-8

"""
    MediaStore API

    MediaStore API for MediaStore  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.media_store_api_features_image_features_upload_to_generic_store_request import MediaStoreAPIFeaturesImageFeaturesUploadToGenericStoreRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestMediaStoreAPIFeaturesImageFeaturesUploadToGenericStoreRequest(unittest.TestCase):
    """MediaStoreAPIFeaturesImageFeaturesUploadToGenericStoreRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediaStoreAPIFeaturesImageFeaturesUploadToGenericStoreRequest(self):
        """Test MediaStoreAPIFeaturesImageFeaturesUploadToGenericStoreRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.media_store_api_features_image_features_upload_to_generic_store_request.MediaStoreAPIFeaturesImageFeaturesUploadToGenericStoreRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
