# coding: utf-8

"""
    MediaStore API

    MediaStore API for MediaStore  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.media_store_api_features_generic_store_features_generic_image_dto import MediaStoreAPIFeaturesGenericStoreFeaturesGenericImageDto  # noqa: E501
from swagger_client.rest import ApiException


class TestMediaStoreAPIFeaturesGenericStoreFeaturesGenericImageDto(unittest.TestCase):
    """MediaStoreAPIFeaturesGenericStoreFeaturesGenericImageDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediaStoreAPIFeaturesGenericStoreFeaturesGenericImageDto(self):
        """Test MediaStoreAPIFeaturesGenericStoreFeaturesGenericImageDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.media_store_api_features_generic_store_features_generic_image_dto.MediaStoreAPIFeaturesGenericStoreFeaturesGenericImageDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
