# coding: utf-8

"""
    MediaStore API

    MediaStore API for MediaStore  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.external_task_api import ExternalTaskApi  # noqa: E501
from swagger_client.rest import ApiException


class TestExternalTaskApi(unittest.TestCase):
    """ExternalTaskApi unit test stubs"""

    def setUp(self):
        self.api = ExternalTaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_external_task_get_image_medie_id_get(self):
        """Test case for external_task_get_image_medie_id_get

        """
        pass

    def test_external_task_get_images_get(self):
        """Test case for external_task_get_images_get

        """
        pass

    def test_external_task_get_images_order_number_get(self):
        """Test case for external_task_get_images_order_number_get

        """
        pass

    def test_external_task_images_fetched_post(self):
        """Test case for external_task_images_fetched_post

        """
        pass

    def test_external_task_order_complete_order_number_post(self):
        """Test case for external_task_order_complete_order_number_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
