# coding: utf-8

"""
    MediaStore API

    MediaStore API for MediaStore  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.generic_store_api import GenericStoreApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGenericStoreApi(unittest.TestCase):
    """GenericStoreApi unit test stubs"""

    def setUp(self):
        self.api = GenericStoreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_genericstore_id_get(self):
        """Test case for genericstore_id_get

        Gets a list of images for a given id (internalID, mediaGroupID or mediaGroupName)  # noqa: E501
        """
        pass

    def test_genericstore_id_image_get(self):
        """Test case for genericstore_id_image_get

        Gets the binary file for single image.  # noqa: E501
        """
        pass

    def test_genericstore_internalid_id_get(self):
        """Test case for genericstore_internalid_id_get

        Gets a list of images for a given internal id  # noqa: E501
        """
        pass

    def test_genericstore_mediagroup_id_get(self):
        """Test case for genericstore_mediagroup_id_get

        Gets a list of images for a given media group id  # noqa: E501
        """
        pass

    def test_genericstore_mediagroupname_name_get(self):
        """Test case for genericstore_mediagroupname_name_get

        Gets a list of images for a given media group name  # noqa: E501
        """
        pass

    def test_genericstore_productgroup_id_get(self):
        """Test case for genericstore_productgroup_id_get

        Obsolete (use /genericstore/mediagroup/id). Gets a list of images for a given product group id  # noqa: E501
        """
        pass

    def test_genericstore_productgroupname_name_get(self):
        """Test case for genericstore_productgroupname_name_get

        Obsolete (use /genericstore/mediagroupname). Gets a list of images for a given product group name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
