# coding: utf-8

"""
    MediaStore API

    MediaStore API for MediaStore  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.token_api import TokenApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self):
        self.api = TokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_products_getapitoken_get(self):
        """Test case for products_getapitoken_get

        Method that returns a CDN accesstoken for a user for all endpoints.  # noqa: E501
        """
        pass

    def test_products_gettoken_get(self):
        """Test case for products_gettoken_get

        Method that returns a CDN accesstoken for a user for the /products endpoint.  # noqa: E501
        """
        pass

    def test_products_getuserhash_get(self):
        """Test case for products_getuserhash_get

        Get the user part of CDN-url.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
