# coding: utf-8

"""
    MediaStore API

    MediaStore API for MediaStore  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'medie_id': 'int',
        'image_url': 'str',
        'template_number': 'str',
        'order_number': 'int'
    }

    attribute_map = {
        'medie_id': 'medieID',
        'image_url': 'imageUrl',
        'template_number': 'templateNumber',
        'order_number': 'orderNumber'
    }

    def __init__(self, medie_id=None, image_url=None, template_number=None, order_number=None):  # noqa: E501
        """MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto - a model defined in Swagger"""  # noqa: E501
        self._medie_id = None
        self._image_url = None
        self._template_number = None
        self._order_number = None
        self.discriminator = None
        if medie_id is not None:
            self.medie_id = medie_id
        if image_url is not None:
            self.image_url = image_url
        if template_number is not None:
            self.template_number = template_number
        if order_number is not None:
            self.order_number = order_number

    @property
    def medie_id(self):
        """Gets the medie_id of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501


        :return: The medie_id of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501
        :rtype: int
        """
        return self._medie_id

    @medie_id.setter
    def medie_id(self, medie_id):
        """Sets the medie_id of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.


        :param medie_id: The medie_id of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501
        :type: int
        """

        self._medie_id = medie_id

    @property
    def image_url(self):
        """Gets the image_url of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501


        :return: The image_url of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        """Sets the image_url of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.


        :param image_url: The image_url of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501
        :type: str
        """

        self._image_url = image_url

    @property
    def template_number(self):
        """Gets the template_number of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501


        :return: The template_number of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501
        :rtype: str
        """
        return self._template_number

    @template_number.setter
    def template_number(self, template_number):
        """Sets the template_number of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.


        :param template_number: The template_number of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501
        :type: str
        """

        self._template_number = template_number

    @property
    def order_number(self):
        """Gets the order_number of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501


        :return: The order_number of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501
        :rtype: int
        """
        return self._order_number

    @order_number.setter
    def order_number(self, order_number):
        """Sets the order_number of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.


        :param order_number: The order_number of this MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto.  # noqa: E501
        :type: int
        """

        self._order_number = order_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MediaStoreAPIFeaturesExternalTaskFeatureExternalTaskDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
